[tool.poetry]
name = "claude-agents-sdk-stuff"
version = "0.1.0"
description = ""
authors = ["Sean Muirhead <smmuirhead100@berkeley.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
pydantic = "^2.12.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
